[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "hello_world"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    'timefold == 999-dev0',
    'pytest == 8.2.2'
]


[project.scripts]
run-app = "hello_world:main"
